# Generated by Django 5.2.4 on 2025-08-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_vendor_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="processing",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="life",
            field=models.PositiveIntegerField(default=0, help_text="HSD"),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_count",
            field=models.PositiveIntegerField(default=0, help_text="Số lượng tồn kho"),
        ),
    ]
