# Generated by Django 5.1.7 on 2025-08-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_cartorderproducts_image"),
        ("core", "0007_vendor_vendor_active"),
    ]

    operations = []
