# Generated by Django 5.2.4 on 2025-08-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_wishlist_model'),
        ('core', '0007_vendor_vendor_active'),
        ('core', '0008_merge_20250824_1548'),
    ]

    operations = []
