# Generated by Django 5.2.4 on 2025-08-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_product_status_uuidtaggeditem_and_more'),
        ('core', '0009_merge_0007_wishlist_model_0008_merge_20250824_1548'),
    ]

    operations = []
